import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
const output=path.resolve(process.env.BASTION_QA_OUTPUT||'bastion-qa-results');
const report=JSON.parse(fs.readFileSync(path.join(output,'report.json'),'utf8'));
assert.equal(report.result,'PASS');
const box=report.fightCanvas;
const width=Math.floor(box.width/2)*2,height=Math.floor(box.height/2)*2,x=Math.floor(box.x/2)*2,y=Math.ceil(box.y/2)*2;
const start=Math.max(0,report.duel.videoStartSeconds-.5),duration=report.duel.videoEndSeconds-start+.3;
const args=['-hide_banner','-y','-i',path.join(output,report.video),'-ss',String(start),'-t',String(duration),'-vf',`crop=${width}:${height}:${x}:${y}`,'-an','-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p','-movflags','+faststart',path.join(output,'battle.mp4')];
const result=spawnSync('ffmpeg',args,{encoding:'utf8'});fs.writeFileSync(path.join(output,'video-encode.log'),result.stdout+result.stderr);assert.equal(result.status,0,'ffmpeg failed: see video-encode.log');
report.battleVideo={file:'battle.mp4',source:report.video,trimStartSeconds:start,durationSeconds:duration,crop:{width,height,x,y},note:'Only scene cropping and timeline trimming; no speed-up, interpolation or replacement of the actual rendered gameplay.'};
fs.writeFileSync(path.join(output,'report.json'),JSON.stringify(report,null,2));
